version: '3'
services:
# -----------------  app  -----------------
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    networks:
      - supnex
# -----------------  mongo  -----------------
  mongo:
    image: docker.repos.balad.ir/mongo:7.0.2
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    networks:
      - supnex
    volumes:
      - ./.data/db:/data/db
      - ./.data/configdb:/data/configdb
# -----------------  gui  -----------------
  mongo-express:
    image: docker.repos.balad.ir/mongo-express:1.0.0-20-alpine3.18
    container_name: gui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - supnex
    depends_on:
      - mongo
networks:
  supnex:
    name: supnex
