version: '3'
services:
  # -----------------  app  -----------------
  supnex-api:
    container_name: supnex-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./:/app/
    working_dir: /app
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - supnex
  # -----------------  mongo  -----------------
  mongo:
    image: docker.repos.balad.ir/mongo:7.0.2
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - supnex
    volumes:
      - ./.data/db:/data/db
      - ./.data/configdb:/data/configdb
    # -----------------  redis  -----------------
  redis:
    image: docker.repos.balad.ir/redis:7.2
    container_name: supnex-redis
    depends_on:
      - supnex-api
      - mongo
    ports:
      - "6739:6379"
    networks:
      - supnex
    volumes:
      - ./.data/redis:/data
    restart: unless-stopped
# -----------------  networks  -----------------
networks:
  supnex:
    name: supnex
